# Generated by Django 2.0.7 on 2018-09-23 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaignapp', '0002_auto_20180922_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_deleted', models.DateField(blank=True, null=True)),
                ('type', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_deleted', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_deleted', models.DateField(blank=True, null=True)),
                ('desktop_browser', models.BooleanField()),
                ('iphone', models.BooleanField()),
                ('android', models.BooleanField()),
                ('android_tablet', models.BooleanField()),
                ('ipad', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_deleted', models.DateField(blank=True, null=True)),
                ('type', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='daily_visitors',
            new_name='price_per_day',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='any_address',
        ),
        migrations.AddField(
            model_name='campaign',
            name='unique_visitors',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaignapp.Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='devices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaignapp.Devices'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='gender',
            field=models.CharField(max_length=120),
        ),
        migrations.AddField(
            model_name='campaigninterest',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaignapp.Campaign'),
        ),
        migrations.AddField(
            model_name='campaigninterest',
            name='interest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaignapp.Interest'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='scheduling',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaignapp.Scheduling'),
            preserve_default=False,
        ),
    ]
