# Generated by Django 2.0.3 on 2018-09-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaignapp', '0003_auto_20180923_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='android',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='devices',
            name='android_tablet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='devices',
            name='desktop_browser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='devices',
            name='ipad',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='devices',
            name='iphone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
